<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Anyware.TaskManagement.Domain</RootNamespace>
		<AssemblyName>Anyware.TaskManagement.Domain</AssemblyName>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>
</Project>