<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Anyware.TaskManagement.Infrastructure</RootNamespace>
		<AssemblyName>Anyware.TaskManagement.Infrastructure</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Anyware.TaskManagement.Domain\Anyware.TaskManagement.Domain.csproj" />
		<ProjectReference Include="..\Anyware.TaskManagement.Application\Anyware.TaskManagement.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.11" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.3.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.24" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.3" />
	</ItemGroup>
</Project>