<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Anyware.TaskManagement.Application</RootNamespace>
		<AssemblyName>Anyware.TaskManagement.Application</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Anyware.TaskManagement.Domain\Anyware.TaskManagement.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
	</ItemGroup>
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>Anyware.TaskManagement.Application.Tests</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>Anyware.TaskManagement.API.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
</Project>